### ISSUE TITLE
Writings page feedback

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/melissadelbosque.com#10]
Include thumbnail image with each article and media outlet

**Comment by AdamChlan** [comment]
@budparr I'm thinking she is requesting we pull images from the articles as thumbnails. I have copyright concerns about that. What do you think?

**Comment by budparr** [comment]
Just ask her if she has the right to use the images. Put her response in Podio. Shouldn't be a problem though, but we'll need to record the image credit (just make a parameter for it 

```
---
...
images: 
- /images/image-title.jpg
image_credit: "So and So's name usually under the image on the article"
---
```

access the image in front-end like this:

```
{{ with .Params.images }}
<img src="{{ index . 0 }}" />
{{ end }}
```

**Comment by budparr** [comment]
I flattened the layout to make room for the images. Let me know if you have any issues.
