### ISSUE TITLE
New Cover Images 

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/melissadelbosque.com#2]
![bloodlines](https://user-images.githubusercontent.com/757209/28118575-8cc12508-66df-11e7-9771-b5e7b530e030.jpg)
[fwdimageofbookcover___.zip](https://github.com/theNewDynamic/melissa-del-bosque.com/files/1141996/fwdimageofbookcover___.zip)

**Comment by budparr** [comment]
Thanks!
