### ISSUE TITLE
Create "Writing" page layout

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/melissadelbosque.com#3]
Initial layout should have descriptive data like date published, publication, description. Consider if we should put in a date-based archive (so, a sidebar with years, or whathaveyou), but that doesn't need to be now.

**Comment by budparr** [comment]
@AdamChlan I've got the rest of the site in a design I'm considering, so once you've put up the writings we can discuss showing to Melissa.

**Comment by AdamChlan** [comment]
@budparr and we discussed this being the base theme repo, right? I don't think I have publishing rights to that, which is fine. Do you want me to add into the child theme, and then you can put into base theme?

**Comment by budparr** [comment]
Sure thing
