### ISSUE TITLE
[content] Contact info

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/melissadelbosque.com#4]
I'm noting that there's no instructions about contacting a publicist, speakers bureau, etc. We need to find out if this needs to be on the site. If Melissa wants contact info and/or a contact form as well.

**Comment by AdamChlan** [comment]
Okay, message sent. Will let you know what she says.

**Comment by AdamChlan** [comment]
She said the only contact info she wants is her email - melissadelbosque1@gmail.com

**Comment by AdamChlan** [comment]
Closing this out since we have a new task for contact page
