### ISSUE TITLE
Create Contact Page

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/melissadelbosque.com#5]
Melissa del Bosque
 
Melissadelbosque1@gmail.com
 
Twitter: @MelissaLaLinea
 
For information and publicity regarding Bloodlines: The True Story of a Drug Cartel, the FBI and the Battle for a Horse-Racing Dynasty, please contact:
 
MARTIN WILSON | Senior Publicity Manager
Harper & Ecco, imprints of HarperCollins Publishers
195 Broadway NY, NY 10007
212-207-7170    martin.wilson@harpercollins.com

**Comment by AdamChlan** [comment]
@budparr I have this page content added to a new page in the repo. Thinking it will need design attention next.

**Comment by budparr** [comment]
I added the contact info to the about page and indicated so in the menu. I'm not opposed to having them separate, but there's so little copy for each.

**Comment by AdamChlan** [comment]
I like that better. On my follow up email to her, I'll sell that to her.
