### ISSUE TITLE
Create Events Page(s)

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/melissadelbosque.com#6]
Book People, Austin, Texas, September 18 7:00 p.m. Reading and Signing
Brazos Bookstore, Houston, Texas, October 8, 7:00 p.m. Reading and Signing
Texas Book Festival, Austin, Texas, November 4-5, Reading.

**Comment by AdamChlan** [comment]
@budparr I added these three events. I'm going to follow up with her to see if she knows when and where her event will take place at the TX Book Festival.

**Comment by budparr** [comment]
Thanks. I think the events page looks okay, don't you? That is, really, the overall simplicity and the distinctive typeface?

**Comment by AdamChlan** [comment]
Melissa does not know the exact day/time/location for TX Book Fest, but will let us know. I do think the listing page looks good. Not sure we need the detail page though. It's not really offering much additional info. Maybe we show description in the listing boxes?

**Comment by budparr** [comment]
Right now the detail page doesn't have any details at all. The template is /event/single/ but it should be there already.

We don't explicitly link to the detail page, but it's good to have anyway (generally speaking) so someone could share a specific event.
