### ISSUE TITLE
Homepage - Add more to the excerpt next to the book image

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/melissadelbosque.com#7]
Drugs, money, cartels: this is what FBI rookie Scott Lawson expected when he was sent to the border town of Laredo, but instead he’s deskbound writing intelligence reports about the drug war. Then, one day, Lawson is asked to check out a tip from a source: a horse was sold at an Oklahoma auction for a record-topping price, and the buyer was Miguel Treviño, one of the leaders of the Zetas, Mexico’s most brutal drug cartel. The source suggested that Treviño was laundering money through American quarter horse racing. If this was true, it offered a rookie like Lawson the perfect opportunity to infiltrate the cartel. Lawson teams up with an IRS taskforce and an experienced FBI agent, Alma Perez, and, taking on impossible odds, sets out to take down one of the world’s most fearsome drug lords.

**Comment by AdamChlan** [comment]
@budparr I did this locally, and it is quite a bit of text. Thinking font size would need to drop. Let me know if you want me to get something in place, or you'd like to just handle it.

**Comment by budparr** [comment]
That copy is already on the book page and it's too much for the home page. No one would read it. I put a prominent "read more" link after the description and that should do it.
