### ISSUE TITLE
Homepage feedback

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/melissadelbosque.com#9]
- [x] Shorter banner with landscape photo of the Rio Grande, the international border between Mexico and Texas. Maybe put my photo in square box below near photo of book.
- [x] I would like to use the 4th Rio Grande photo at this link  https://adobe.ly/2tkMQR4
- [x] If it's too difficult to mesh my bio/photo with book I would prefer to have the book and blurbs on opening page then an about tab with a page that includes my photo and bio. (Like at this link https://www.davidgrann.com/about/ )

**Comment by budparr** [comment]
We'll likely do as that last bullet point. I knew the full screen home page image of her was risky, but I wanted to come out with something strong.

**Comment by budparr** [comment]
I did these. We can leave this open until the next round of approval from M.

should have referenced this issue in my commits, but here they are:
a0fec54b3d5d9ce5a0b8d49074f753f6699043b5
032a06a9077b0761e7c2a4a72bd9f8f8ce2cbe86
2b00aa3a147474fbf2a159021eb10ff5e8ce0a08
